//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiServiceApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkiServiceApp.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt angemeldet: ähnelt.
        /// </summary>
        public static string AppLogin_LastLoginsLabel {
            get {
                return ResourceManager.GetString("AppLogin.LastLoginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt verwendet am:  ähnelt.
        /// </summary>
        public static string AppLogin_LastUsedLabel {
            get {
                return ResourceManager.GetString("AppLogin.LastUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string AppLogin_PasswordLabel {
            get {
                return ResourceManager.GetString("AppLogin.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einloggen ähnelt.
        /// </summary>
        public static string AppLogin_SigninButton {
            get {
                return ResourceManager.GetString("AppLogin.SigninButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string AppLogin_SigninLabel {
            get {
                return ResourceManager.GetString("AppLogin.SigninLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        public static string AppLogin_UsernameLabel {
            get {
                return ResourceManager.GetString("AppLogin.UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dashboard ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_DashboardButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.DashboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auftragsinformationen ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_DetailsPageButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.DetailsPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Aufträge ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_ListButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.ListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausloggen ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_LogoutButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_SettingsButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Aufträge ähnelt.
        /// </summary>
        public static string AppShell_FlyoutItem_UserListButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.UserListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Made by Robin and Fokko with ähnelt.
        /// </summary>
        public static string AppShell_Love {
            get {
                return ResourceManager.GetString("AppShell.Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SkiService App ähnelt.
        /// </summary>
        public static string AppShell_Title {
            get {
                return ResourceManager.GetString("AppShell.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst deinen eigenen Account nicht freigeben. Wende dich an den Administrator. ähnelt.
        /// </summary>
        public static string Backend_Error_CANNOT_UNLOCK_SELF {
            get {
                return ResourceManager.GetString("Backend.Error.CANNOT_UNLOCK_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag konnte nicht gefunden werden. ähnelt.
        /// </summary>
        public static string Backend_Error_ENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("Backend.Error.ENTRY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Benutzername oder Passwort ist falsch. ähnelt.
        /// </summary>
        public static string Backend_Error_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("Backend.Error.INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Account ist blockiert. Wende dich an den Administrator. ähnelt.
        /// </summary>
        public static string Backend_Error_USER_LOCKED {
            get {
                return ResourceManager.GetString("Backend.Error.USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Benutzer ist nicht geblockt. ähnelt.
        /// </summary>
        public static string Backend_Error_USER_NOT_LOCKED {
            get {
                return ResourceManager.GetString("Backend.Error.USER_NOT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginnen ähnelt.
        /// </summary>
        public static string Backend_NextState_2 {
            get {
                return ResourceManager.GetString("Backend.NextState.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string Backend_NextState_3 {
            get {
                return ResourceManager.GetString("Backend.NextState.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tief ähnelt.
        /// </summary>
        public static string Backend_Priority_1 {
            get {
                return ResourceManager.GetString("Backend.Priority.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        /// </summary>
        public static string Backend_Priority_2 {
            get {
                return ResourceManager.GetString("Backend.Priority.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hoch ähnelt.
        /// </summary>
        public static string Backend_Priority_3 {
            get {
                return ResourceManager.GetString("Backend.Priority.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kleiner Service ähnelt.
        /// </summary>
        public static string Backend_Service_1 {
            get {
                return ResourceManager.GetString("Backend.Service.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grosser Service ähnelt.
        /// </summary>
        public static string Backend_Service_2 {
            get {
                return ResourceManager.GetString("Backend.Service.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rennski-Service ähnelt.
        /// </summary>
        public static string Backend_Service_3 {
            get {
                return ResourceManager.GetString("Backend.Service.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bindung montieren und einstellen ähnelt.
        /// </summary>
        public static string Backend_Service_4 {
            get {
                return ResourceManager.GetString("Backend.Service.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fell zuschneiden pro Paar ähnelt.
        /// </summary>
        public static string Backend_Service_5 {
            get {
                return ResourceManager.GetString("Backend.Service.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heisswachsen ähnelt.
        /// </summary>
        public static string Backend_Service_6 {
            get {
                return ResourceManager.GetString("Backend.Service.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offen ähnelt.
        /// </summary>
        public static string Backend_State_1 {
            get {
                return ResourceManager.GetString("Backend.State.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Arbeit ähnelt.
        /// </summary>
        public static string Backend_State_2 {
            get {
                return ResourceManager.GetString("Backend.State.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgeschlossen ähnelt.
        /// </summary>
        public static string Backend_State_3 {
            get {
                return ResourceManager.GetString("Backend.State.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stornieren ähnelt.
        /// </summary>
        public static string CancelDialog_Submit {
            get {
                return ResourceManager.GetString("CancelDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die für ähnelt.
        /// </summary>
        public static string CancelDialog_SubTitleMiddle {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitleMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auftrag löschen ähnelt.
        /// </summary>
        public static string CancelDialog_SubTitlePre {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitlePre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bestätigen. ähnelt.
        /// </summary>
        public static string CancelDialog_SubTitleSub {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auftrag stornieren? ähnelt.
        /// </summary>
        public static string CancelDialog_Title {
            get {
                return ResourceManager.GetString("CancelDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übernehmen ähnelt.
        /// </summary>
        public static string CustomListItem_ApplyButton {
            get {
                return ResourceManager.GetString("CustomListItem.ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stornieren ähnelt.
        /// </summary>
        public static string CustomListItem_CancelButton {
            get {
                return ResourceManager.GetString("CustomListItem.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        public static string CustomListItem_ChangeButton {
            get {
                return ResourceManager.GetString("CustomListItem.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag(e) übrig ähnelt.
        /// </summary>
        public static string CustomListItem_DaysLeft {
            get {
                return ResourceManager.GetString("CustomListItem.DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht zugewiesen ähnelt.
        /// </summary>
        public static string CustomListItem_Unassigned {
            get {
                return ResourceManager.GetString("CustomListItem.Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erledigt ähnelt.
        /// </summary>
        public static string Dashboard_Chart_Done {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offen ähnelt.
        /// </summary>
        public static string Dashboard_Chart_Open {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Aufträge ähnelt.
        /// </summary>
        public static string Dashboard_Chart_You {
            get {
                return ResourceManager.GetString("Dashboard.Chart.You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast aktuell noch ähnelt.
        /// </summary>
        public static string Dashboard_SecondarySummary_Pre {
            get {
                return ResourceManager.GetString("Dashboard.SecondarySummary.Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufträge offen ähnelt.
        /// </summary>
        public static string Dashboard_SecondarySummary_Sub {
            get {
                return ResourceManager.GetString("Dashboard.SecondarySummary.Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von ähnelt.
        /// </summary>
        public static string Dashboard_Summary_Middle {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast ähnelt.
        /// </summary>
        public static string Dashboard_Summary_Pre {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abgeschlossenen Aufträgen abgewickelt ähnelt.
        /// </summary>
        public static string Dashboard_Summary_Sub {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        public static string Dialog_Submit {
            get {
                return ResourceManager.GetString("Dialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Überschrift ähnelt.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht Speichern ähnelt.
        /// </summary>
        public static string LogoutDialog_Danger {
            get {
                return ResourceManager.GetString("LogoutDialog.Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string LogoutDialog_Submit {
            get {
                return ResourceManager.GetString("LogoutDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll dieses Konto in der Liste für die Schnell-Anmeldung gespeichert werden, damit die nächste Anmeldung durch einen einzelnen Klick von statten gehen kann? ähnelt.
        /// </summary>
        public static string LogoutDialog_Text {
            get {
                return ResourceManager.GetString("LogoutDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permanent Ausloggen ähnelt.
        /// </summary>
        public static string LogoutDialog_Title {
            get {
                return ResourceManager.GetString("LogoutDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail Adresse ähnelt.
        /// </summary>
        public static string ModifyDialog_EmailLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ModifyDialog_NameLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon ähnelt.
        /// </summary>
        public static string ModifyDialog_PhoneLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priorität ähnelt.
        /// </summary>
        public static string ModifyDialog_PriorityLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dienstleistung ähnelt.
        /// </summary>
        public static string ModifyDialog_ServiceLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.ServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string ModifyDialog_StateLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string ModifyDialog_Submit {
            get {
                return ResourceManager.GetString("ModifyDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auftrag ändern ähnelt.
        /// </summary>
        public static string ModifyDialog_Title {
            get {
                return ResourceManager.GetString("ModifyDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stornieren ähnelt.
        /// </summary>
        public static string OrderDetailPage_CancelButton {
            get {
                return ResourceManager.GetString("OrderDetailPage.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        public static string OrderDetailPage_ChangeButton {
            get {
                return ResourceManager.GetString("OrderDetailPage.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kundenname ähnelt.
        /// </summary>
        public static string OrderDetailPage_CustomerNameLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestellt am: ähnelt.
        /// </summary>
        public static string OrderDetailPage_DateLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string OrderDetailPage_EmailLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon ähnelt.
        /// </summary>
        public static string OrderDetailPage_PhoneLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für die Erledigung des Auftrages sind noch ähnelt.
        /// </summary>
        public static string OrderDetailPage_PreDaysLeft {
            get {
                return ResourceManager.GetString("OrderDetailPage.PreDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        public static string OrderList_Search {
            get {
                return ResourceManager.GetString("OrderList.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login immer speichern ähnelt.
        /// </summary>
        public static string SettingsPage_AlwaysSaveLoginLabel {
            get {
                return ResourceManager.GetString("SettingsPage.AlwaysSaveLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stornieren in Listenansicht ähnelt.
        /// </summary>
        public static string SettingsPage_CancelInListViewLabel {
            get {
                return ResourceManager.GetString("SettingsPage.CancelInListViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf ALLEN Geräten ausloggen ähnelt.
        /// </summary>
        public static string SettingsPage_LogoutOnAllDevicesButton {
            get {
                return ResourceManager.GetString("SettingsPage.LogoutOnAllDevicesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        /// </summary>
        public static string SettingsPage_Theme_Dark {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        /// </summary>
        public static string SettingsPage_Theme_Light {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string SettingsPage_Theme_System {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme ähnelt.
        /// </summary>
        public static string SettingsPage_ThemeLabel {
            get {
                return ResourceManager.GetString("SettingsPage.ThemeLabel", resourceCulture);
            }
        }
    }
}
