//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiServiceApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkiServiceApp.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt angemeldet:.
        /// </summary>
        public static string AppLogin_LastLoginsLabel {
            get {
                return ResourceManager.GetString("AppLogin.LastLoginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt verwendet am: .
        /// </summary>
        public static string AppLogin_LastUsedLabel {
            get {
                return ResourceManager.GetString("AppLogin.LastUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string AppLogin_PasswordLabel {
            get {
                return ResourceManager.GetString("AppLogin.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string AppLogin_SigninButton {
            get {
                return ResourceManager.GetString("AppLogin.SigninButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string AppLogin_SigninLabel {
            get {
                return ResourceManager.GetString("AppLogin.SigninLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string AppLogin_UsernameLabel {
            get {
                return ResourceManager.GetString("AppLogin.UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string AppShell_FlyoutItem_DashboardButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.DashboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragsinformationen.
        /// </summary>
        public static string AppShell_FlyoutItem_DetailsPageButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.DetailsPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Aufträge.
        /// </summary>
        public static string AppShell_FlyoutItem_ListButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.ListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string AppShell_FlyoutItem_LogoutButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string AppShell_FlyoutItem_SettingsButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Aufträge.
        /// </summary>
        public static string AppShell_FlyoutItem_UserListButton {
            get {
                return ResourceManager.GetString("AppShell.FlyoutItem.UserListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Robin and Fokko with.
        /// </summary>
        public static string AppShell_Love {
            get {
                return ResourceManager.GetString("AppShell.Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkiService App.
        /// </summary>
        public static string AppShell_Title {
            get {
                return ResourceManager.GetString("AppShell.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst deinen eigenen Account nicht freigeben. Wende dich an den Administrator..
        /// </summary>
        public static string Backend_Error_CANNOT_UNLOCK_SELF {
            get {
                return ResourceManager.GetString("Backend.Error.CANNOT_UNLOCK_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag konnte nicht gefunden werden..
        /// </summary>
        public static string Backend_Error_ENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("Backend.Error.ENTRY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der eingegebene Benutzername oder Passwort ist falsch..
        /// </summary>
        public static string Backend_Error_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("Backend.Error.INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Account ist blockiert. Wende dich an den Administrator..
        /// </summary>
        public static string Backend_Error_USER_LOCKED {
            get {
                return ResourceManager.GetString("Backend.Error.USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer ist nicht geblockt..
        /// </summary>
        public static string Backend_Error_USER_NOT_LOCKED {
            get {
                return ResourceManager.GetString("Backend.Error.USER_NOT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginnen.
        /// </summary>
        public static string Backend_NextState_2 {
            get {
                return ResourceManager.GetString("Backend.NextState.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string Backend_NextState_3 {
            get {
                return ResourceManager.GetString("Backend.NextState.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tief.
        /// </summary>
        public static string Backend_Priority_1 {
            get {
                return ResourceManager.GetString("Backend.Priority.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Backend_Priority_2 {
            get {
                return ResourceManager.GetString("Backend.Priority.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoch.
        /// </summary>
        public static string Backend_Priority_3 {
            get {
                return ResourceManager.GetString("Backend.Priority.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleiner Service.
        /// </summary>
        public static string Backend_Service_1 {
            get {
                return ResourceManager.GetString("Backend.Service.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grosser Service.
        /// </summary>
        public static string Backend_Service_2 {
            get {
                return ResourceManager.GetString("Backend.Service.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rennski-Service.
        /// </summary>
        public static string Backend_Service_3 {
            get {
                return ResourceManager.GetString("Backend.Service.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindung montieren und einstellen.
        /// </summary>
        public static string Backend_Service_4 {
            get {
                return ResourceManager.GetString("Backend.Service.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fell zuschneiden pro Paar.
        /// </summary>
        public static string Backend_Service_5 {
            get {
                return ResourceManager.GetString("Backend.Service.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heisswachsen.
        /// </summary>
        public static string Backend_Service_6 {
            get {
                return ResourceManager.GetString("Backend.Service.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offen.
        /// </summary>
        public static string Backend_State_1 {
            get {
                return ResourceManager.GetString("Backend.State.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Arbeit.
        /// </summary>
        public static string Backend_State_2 {
            get {
                return ResourceManager.GetString("Backend.State.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossen.
        /// </summary>
        public static string Backend_State_3 {
            get {
                return ResourceManager.GetString("Backend.State.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        public static string CancelDialog_Submit {
            get {
                return ResourceManager.GetString("CancelDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to für.
        /// </summary>
        public static string CancelDialog_SubTitleMiddle {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitleMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag löschen.
        /// </summary>
        public static string CancelDialog_SubTitlePre {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitlePre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestätigen..
        /// </summary>
        public static string CancelDialog_SubTitleSub {
            get {
                return ResourceManager.GetString("CancelDialog.SubTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag stornieren?.
        /// </summary>
        public static string CancelDialog_Title {
            get {
                return ResourceManager.GetString("CancelDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übernehmen.
        /// </summary>
        public static string CustomListItem_ApplyButton {
            get {
                return ResourceManager.GetString("CustomListItem.ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        public static string CustomListItem_CancelButton {
            get {
                return ResourceManager.GetString("CustomListItem.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern.
        /// </summary>
        public static string CustomListItem_ChangeButton {
            get {
                return ResourceManager.GetString("CustomListItem.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(e) übrig.
        /// </summary>
        public static string CustomListItem_DaysLeft {
            get {
                return ResourceManager.GetString("CustomListItem.DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht zugewiesen.
        /// </summary>
        public static string CustomListItem_Unassigned {
            get {
                return ResourceManager.GetString("CustomListItem.Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt.
        /// </summary>
        public static string Dashboard_Chart_Done {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offen.
        /// </summary>
        public static string Dashboard_Chart_Open {
            get {
                return ResourceManager.GetString("Dashboard.Chart.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Aufträge.
        /// </summary>
        public static string Dashboard_Chart_You {
            get {
                return ResourceManager.GetString("Dashboard.Chart.You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast aktuell noch.
        /// </summary>
        public static string Dashboard_SecondarySummary_Pre {
            get {
                return ResourceManager.GetString("Dashboard.SecondarySummary.Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufträge offen.
        /// </summary>
        public static string Dashboard_SecondarySummary_Sub {
            get {
                return ResourceManager.GetString("Dashboard.SecondarySummary.Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        public static string Dashboard_Summary_Middle {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast.
        /// </summary>
        public static string Dashboard_Summary_Pre {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abgeschlossenen Aufträgen abgewickelt.
        /// </summary>
        public static string Dashboard_Summary_Sub {
            get {
                return ResourceManager.GetString("Dashboard.Summary.Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        public static string Dialog_Submit {
            get {
                return ResourceManager.GetString("Dialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Überschrift.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht Speichern.
        /// </summary>
        public static string LogoutDialog_Danger {
            get {
                return ResourceManager.GetString("LogoutDialog.Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string LogoutDialog_Submit {
            get {
                return ResourceManager.GetString("LogoutDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll dieses Konto in der Liste für die Schnell-Anmeldung gespeichert werden, damit die nächste Anmeldung durch einen einzelnen Klick von statten gehen kann?.
        /// </summary>
        public static string LogoutDialog_Text {
            get {
                return ResourceManager.GetString("LogoutDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Ausloggen.
        /// </summary>
        public static string LogoutDialog_Title {
            get {
                return ResourceManager.GetString("LogoutDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse.
        /// </summary>
        public static string ModifyDialog_EmailLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ModifyDialog_NameLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string ModifyDialog_PhoneLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität.
        /// </summary>
        public static string ModifyDialog_PriorityLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstleistung.
        /// </summary>
        public static string ModifyDialog_ServiceLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.ServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ModifyDialog_StateLabel {
            get {
                return ResourceManager.GetString("ModifyDialog.StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string ModifyDialog_Submit {
            get {
                return ResourceManager.GetString("ModifyDialog.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrag ändern.
        /// </summary>
        public static string ModifyDialog_Title {
            get {
                return ResourceManager.GetString("ModifyDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        public static string OrderDetailPage_CancelButton {
            get {
                return ResourceManager.GetString("OrderDetailPage.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern.
        /// </summary>
        public static string OrderDetailPage_ChangeButton {
            get {
                return ResourceManager.GetString("OrderDetailPage.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenname.
        /// </summary>
        public static string OrderDetailPage_CustomerNameLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestellt am:.
        /// </summary>
        public static string OrderDetailPage_DateLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string OrderDetailPage_EmailLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string OrderDetailPage_PhoneLabel {
            get {
                return ResourceManager.GetString("OrderDetailPage.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für die Erledigung des Auftrages sind noch.
        /// </summary>
        public static string OrderDetailPage_PreDaysLeft {
            get {
                return ResourceManager.GetString("OrderDetailPage.PreDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login immer speichern.
        /// </summary>
        public static string SettingsPage_AlwaysSaveLoginLabel {
            get {
                return ResourceManager.GetString("SettingsPage.AlwaysSaveLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren in Listenansicht.
        /// </summary>
        public static string SettingsPage_CancelInListViewLabel {
            get {
                return ResourceManager.GetString("SettingsPage.CancelInListViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf ALLEN Geräten ausloggen.
        /// </summary>
        public static string SettingsPage_LogoutOnAllDevicesButton {
            get {
                return ResourceManager.GetString("SettingsPage.LogoutOnAllDevicesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkel.
        /// </summary>
        public static string SettingsPage_Theme_Dark {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hell.
        /// </summary>
        public static string SettingsPage_Theme_Light {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SettingsPage_Theme_System {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_ThemeLabel {
            get {
                return ResourceManager.GetString("SettingsPage.ThemeLabel", resourceCulture);
            }
        }
    }
}
